### ISSUE TITLE
Mon Sept 19th 2016 - Nomination

### ISSUE THREAD

**Issue by shazron** [cordova/new_committer_and_pmc#1]
**DO NOT** add the potential candidate's name here since a vote can fail, an invitation can be rejected, or the Apache Board can veto PMC inclusion (but not the vote for a committer).

See the [README](../README.md) for details on each of the steps.
# Checklist
- [x] 1. Send a [VOTE] thread to private@ [[details]](https://github.com/cordova/new_committer_and_pmc#1-send-a-vote-thread-to-private)
- [x] 2. Wait three days or when there is a clear consensus, then close the [VOTE] [[details]](https://github.com/cordova/new_committer_and_pmc#2-wait-three-days-or-when-there-is-a-clear-consensus-then-close-the-vote)
- [x] 3. Send an Invite email to the community member, cc private@ [[details]](https://github.com/cordova/new_committer_and_pmc#3-send-an-invite-email-to-the-community-member-cc-private)
- [x] 4. Send a PMC Notice to board@, and cc private@ [[details]](https://github.com/cordova/new_committer_and_pmc#4-send-a-pmc-notice-to-board-and-cc-private)
- [x] 5. When the new committer accepts the invite, create a new account for the user (PMC Chair only) [[details]](https://github.com/cordova/new_committer_and_pmc#5-when-the-new-committer-accepts-the-invite-create-a-new-account-for-the-user-pmc-chair-only)
- [x] 6. Once 72 hours has elapsed from the board@ notice, add the committer to the PMC committee-info.txt file (any PMC member) [[details]](https://github.com/cordova/new_committer_and_pmc#6-once-72-hours-has-elapsed-from-the-board-notice-add-the-committer-to-the-pmc-committee-infotxt-file-any-pmc-member)
- [x] 7. Once 72 hours has elapsed from the board@ notice, add the committer to the PMC LDAP records (PMC Chair only) [[details]](https://github.com/cordova/new_committer_and_pmc#7-once-72-hours-has-elapsed-from-the-board-notice-add-the-committer-to-the-pmc-ldap-records-pmc-chair-only)
- [x] 8. Add the PMC member to the private@ list [[details]](https://github.com/cordova/new_committer_and_pmc/blob/master/README.md#8-automatically-subscribe-the-new-pmc-member-to-the-private-list)
- [x] Close this issue with a resolution note

**Comment by shazron** [comment]
Congrats to the newest committer and PMC Member of Apache Cordova, @dpogue !
