### ISSUE TITLE
New committer and pmc member (July 16th 2018)

### ISSUE THREAD

**Issue by shazron** [cordova/new_committer_and_pmc#9]
**DO NOT** add the potential candidate's name here since a vote can fail, an invitation can be rejected, or the Apache Board can veto PMC inclusion (but not the vote for a committer).

See the [README](../README.md) for details on each of the steps.

# Checklist

- [x] 1. Send a [VOTE] thread to private@ [[details]](https://github.com/apache/cordova-new-committer-and-pmc#1-send-a-vote-thread-to-private)
- [x] 2. Wait three days (72 hours) or when there is a clear consensus, then close the [VOTE] [[details]](https://github.com/apache/cordova-new-committer-and-pmc/blob/master/README.md#2-wait-three-days-72-hours-or-when-there-is-a-clear-consensus-then-close-the-vote)
- [x] 3. Send an Invite email to the community member, cc private@ [[details]](https://github.com/apache/cordova-new-committer-and-pmc#3-send-an-invite-email-to-the-community-member-cc-private)
- [x] 4. Send a PMC Notice to board@, and cc private@ [[details]](https://github.com/apache/cordova-new-committer-and-pmc#4-send-a-pmc-notice-to-board-and-cc-private)
- [x] 5. When the new committer accepts the invite, create a new account for the user (PMC Chair only) [[details]](https://github.com/apache/cordova-new-committer-and-pmc#5-when-the-new-committer-accepts-the-invite-create-a-new-account-for-the-user-pmc-chair-only)
- [x] 6. Once 72 hours has elapsed from the board@ notice, add the committer to the PMC committee-info.txt file and LDAP (PMC Chair)[[details]](https://github.com/apache/cordova-new-committer-and-pmc#6-once-72-hours-has-elapsed-from-the-board-notice-add-the-committer-to-the-pmc-committee-infotxt-file-and-ldap-any-pmc-chair)
- [x] 7. Add the PMC member to the private@ list [[details]](https://github.com/apache/cordova-new-committer-and-pmc#7-automatically-subscribe-the-new-pmc-member-to-the-private-list)
- [x] Close this issue with a resolution note

**Comment by purplecabbage** [comment]
+1, +1

**Comment by shazron** [comment]
Welcome to Cordova @erisu, @menardi, and @knight9999 !
